export enum Table {
  Users = 'users',
  Schools = 'schools',
  Subjects = 'school_subjects',
  Countries = 'countries',
  Degrees = 'school_degrees',
  StudyPlans = 'school_plans',
  Courses = 'courses',
  CourseTeachers = 'course_teachers',
  Genders = 'genders',
  Teachers = 'school_teachers',
  Groups = 'school_groups',
  AssignmentTypes = 'assignment_types',
  UserProfiles = 'user_profiles',
  Assignments = 'assignments',
  AssignmentsView = 'active_assignments',
  GroupAssignments = 'group_assignments',
  Grades = 'grades',
  GradeBuckets = 'grade_buckets',
  Periods = 'periods',
  SchoolUsers = 'school_users',
  Levels = 'levels',
  GroupStudents = 'group_students',
  Channels = 'channels',
}
